"use client";

import LegalPage from "../../components/LegalPage";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use" updated="31 August 2026">
      <p className="todo">
        Draft for legal review. Bracketed items need filling in once the company
        exists, and a lawyer should read this before Zodi accepts payment.
      </p>

      <p>
        These terms are the agreement between you and <strong>[COMPANY NAME]</strong>{" "}
        (&ldquo;we&rdquo;, &ldquo;us&rdquo;) about your use of Zodi. By creating an
        account you accept them. If you don&rsquo;t, please don&rsquo;t use Zodi.
      </p>

      <h2>What Zodi is &mdash; and what it isn&rsquo;t</h2>

      <div className="callout">
        <p>
          <strong>Zodi is for entertainment and self-reflection.</strong> It is not
          advice. Nothing Zodi says is medical, psychological, legal, financial, or
          professional advice, and you should not treat it as such or rely on it to
          make decisions that matter.
        </p>
      </div>

      <p>
        Zodi calculates real astronomical positions and interprets them. The
        calculations are accurate; the interpretations are a point of view about
        symbols, not statements of fact about your life, your future, or anybody
        else&rsquo;s.
      </p>

      <p>
        <strong>Answers are generated by artificial intelligence.</strong> They may
        be inaccurate, inconsistent, or simply wrong, and two similar questions may
        get different answers. Please use your own judgement.
      </p>

      <div className="callout">
        <p>
          <strong>If you are struggling, please talk to someone real.</strong> Zodi
          is not a crisis service, a therapist, or a substitute for care. If you are
          in distress or thinking about harming yourself, contact your local
          emergency services or a crisis line in your country.
        </p>
      </div>

      <h2>Who can use Zodi</h2>
      <p>
        You must be at least <strong>18</strong> to use Zodi. By creating an account
        you confirm you are. We don&rsquo;t knowingly collect information from
        children, and we&rsquo;ll delete any account we find belongs to one.
      </p>

      <h2>Your account</h2>
      <p>
        You&rsquo;re responsible for keeping your password to yourself and for what
        happens under your account. Give us accurate information &mdash; particularly
        your birth details, since the whole reading is built on them. Tell us
        promptly if you think someone else has got into your account.
      </p>
      <p>
        One account per person. Don&rsquo;t share or sell access.
      </p>

      <h2>Using Zodi fairly</h2>
      <p>Please don&rsquo;t:</p>
      <ul>
        <li>Use Zodi for anything unlawful, or to harass or harm anyone</li>
        <li>
          Try to break, overload, scrape, or reverse-engineer the service, or get
          around usage limits
        </li>
        <li>
          Resell Zodi&rsquo;s output as your own service, or use it to train another
          model
        </li>
        <li>
          Upload someone else&rsquo;s personal details without a good reason to have
          them &mdash; when you save another person&rsquo;s birth information, you are
          telling us you&rsquo;re entitled to
        </li>
      </ul>
      <p>
        We may suspend or close accounts that break these rules, usually with notice
        unless the situation is serious.
      </p>

      <h2>Plans and payment</h2>
      <p>
        Zodi has a free tier and paid plans. Paid plans are billed in advance and
        renew automatically until you cancel. Prices are shown before you pay, and
        include tax where it applies.
      </p>
      <p>
        <strong>You can cancel at any time.</strong> Cancelling stops the next
        renewal; you keep access until the end of the period you&rsquo;ve already
        paid for. We don&rsquo;t charge a cancellation fee.
      </p>
      <p>
        If you are a consumer in the EU or UK you normally have{" "}
        <strong>14 days to change your mind</strong> about a digital purchase. Where
        you ask us to start immediately and acknowledge you&rsquo;re giving up that
        right, it no longer applies to the part you&rsquo;ve used.
      </p>
      <p>
        We may change prices, but not for a period you&rsquo;ve already paid for. If
        prices change we&rsquo;ll tell you before your next renewal so you can cancel
        if you&rsquo;d rather.
      </p>
      <p className="todo">
        [Confirm the refund position with a lawyer once the payment provider is
        chosen &mdash; consumer withdrawal rights differ by country.]
      </p>

      <h2>Usage limits</h2>
      <p>
        Each plan includes an allowance. Running out isn&rsquo;t a fault &mdash;
        you&rsquo;ll be told, and you can wait for it to reset or move to a larger
        plan. We may adjust allowances, and we&rsquo;ll give notice before reducing
        one on a paid plan.
      </p>

      <h2>Your content, and ours</h2>
      <p>
        <strong>What you write stays yours.</strong> You give us permission to
        process it only so far as we need to run Zodi and answer you &mdash; including
        sending it to the AI providers described in our{" "}
        <a href="/privacy">Privacy Policy</a>.
      </p>
      <p>
        Readings Zodi produces for you are yours to keep, share, and screenshot.
      </p>
      <p>
        Zodi itself &mdash; the software, the astrological interpretation system, the
        name and the design &mdash; belongs to us. Using Zodi doesn&rsquo;t give you
        any rights in it.
      </p>

      <h2>Availability</h2>
      <p>
        We&rsquo;ll try to keep Zodi running, but we can&rsquo;t promise it will
        always be available or uninterrupted. We may change or discontinue features.
        If we discontinue a paid feature you&rsquo;ve paid for, we&rsquo;ll refund the
        unused part.
      </p>

      <h2>Liability</h2>
      <p>
        Zodi is provided &ldquo;as is&rdquo;. To the extent the law allows, we
        aren&rsquo;t liable for decisions you make based on a reading, for indirect or
        consequential loss, or for anything beyond the amount you paid us in the
        twelve months before the claim.
      </p>
      <p>
        Nothing here limits liability that can&rsquo;t legally be limited &mdash;
        including for death or personal injury caused by negligence, or for fraud.
        If you are a consumer, your statutory rights are unaffected.
      </p>

      <h2>Ending things</h2>
      <p>
        You can close your account whenever you like, and we&rsquo;ll delete your data
        as described in the <a href="/privacy">Privacy Policy</a>. We may close your
        account if you seriously or repeatedly break these terms.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms. If a change materially affects you we&rsquo;ll tell
        you by email or in the app before it takes effect. Continuing to use Zodi
        after that means you accept the new version.
      </p>

      <h2>Law and disputes</h2>
      <p>
        These terms are governed by the law of <strong>[JURISDICTION]</strong>, and
        disputes go to its courts. If you are a consumer, you keep the protection of
        the mandatory law of the country you live in, and you may be able to use an
        online dispute resolution platform.
      </p>

      <h2>Contact</h2>
      <p>
        <strong>[COMPANY NAME]</strong>
        <br />
        [REGISTERED ADDRESS]
        <br />
        [CONTACT EMAIL]
      </p>
    </LegalPage>
  );
}
